fruits = ["pomme", "banane", "orange"]
print("Liste de fruits : ", fruits)
print("Premier fruit :", fruits[0])
print("Ajout du fruit Kiwi en fin de liste")
fruits.append("kiwi")
print("Liste de fruits mise à jour : ", fruits)
print("Suppression du fruit orange de la liste")
fruits.remove("orange")
print("Liste de fruits après suppression : ", fruits)
print("Longueur de la liste de fruits est : ", len(fruits))
fruits.sort()
print("Liste de fruits triée : ", fruits)
print("Vérification si 'banane' est dans la liste :", "banane" in fruits)
print("Index de 'kiwi' dans la liste :", fruits.index("kiwi"))